### ISSUE TITLE
Left menu margin does not work.

### ISSUE THREAD

**Issue by alirizaadiyahsi** [alirizaadiyahsi/Kodkod#35]
Even though add required css

```css
.main-nav {
    position: fixed;
    top: 50px;
    left: 0;
    right: 0;
    z-index: 1;
}
```
